AllCops:
  NewCops: enable

Layout/LineLength:
  AllowHeredoc: true
  AllowURI: true
  Max: 120
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Naming/VariableNumber:
  CheckSymbols: false

Style/CaseEquality:
  AllowOnConstant: true
Style/Documentation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/SymbolArray:
  Enabled: false