inherit_from: .rubocop_todo.yml

# Classes can contain many methods and it is normal for them
# to be long, so allow a higher class length.
Metrics/ClassLength:
  Max: 1024

# The default allowed method length (10) is ridiculously low.
Metrics/MethodLength:
  CountComments: false
  Max: 64
