# Classes can contain many methods and it is normal for them
# to be long, so allow a higher class length.
Metrics/ClassLength:
  Max: 1024

# The default allowed method length (10) is ridiculously low.
Metrics/MethodLength:
  CountComments: false
  Max: 64

# Disallow long lines, except for "if" and "unless" statements.
Metrics/LineLength:
  AllowHeredoc: true
  AllowURI: true
  IgnoredPatterns:
    - '\sif|unless\s'

# Assignment Branches and Conditions metric.
# See http://c2.com/cgi/wiki?AbcMetric
Metrics/AbcSize:
  Max: 60

# Adds one for every decision point.
Metrics/CyclomaticComplexity:
  Max: 10

# See https://www.rubydoc.info/gems/rubocop/0.27.0/RuboCop/Cop/Metrics/PerceivedComplexity
Metrics/PerceivedComplexity:
  Max: 10
